import './globals.css'
import { Poppins,Oswald} from 'next/font/google'
import localFont from "next/font/local";
import Header from './components/Header';

const lato = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-lato'
})

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

const bebas = localFont({
  src: [
    {
      path: "../public/fonts/FuturaHeavy.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/futuraLight.ttf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-bebas",
});

export const metadata = {
  title: 'Tateno Pictures',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-ttn-black">
      <body
        className={`${lato.variable} ${bebas.variable} ${oswald.variable} font-body w-screen overflow-x-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
